server:
  port: 8000
spring:
  application:
    name: cambio-service  
  cloud: #RESOLVE PROBLEMA DE NAO INICIAIR
    config:
      enabled: false
  datasource:
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
      username: root
      password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDiealect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: cambio-service
    user: root
    password: admin
    